inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
  - spec/support/aws*

Style/OpenStructUse:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'ruby-sfn-local.gemspec'